# Generated by Django 4.2.7 on 2025-11-09 11:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtificialInsemination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai_date', models.DateField(default=django.utils.timezone.now)),
                ('ai_time', models.TimeField(default=django.utils.timezone.now)),
                ('bull_breed', models.CharField(help_text='Breed of bull used for AI', max_length=100)),
                ('bull_id', models.CharField(blank=True, help_text='Bull identification number', max_length=100, null=True)),
                ('semen_source', models.CharField(blank=True, max_length=200, null=True)),
                ('heat_detection_date', models.DateField(help_text='Date when cow was in heat')),
                ('technician_name', models.CharField(blank=True, max_length=100, null=True)),
                ('success_status', models.CharField(default='Pending', help_text='Pending/Confirmed/Failed', max_length=50)),
                ('expected_calving_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_records', to='core.cow')),
            ],
            options={
                'ordering': ['-ai_date'],
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('qualification', models.CharField(max_length=200)),
                ('specialization', models.CharField(blank=True, max_length=200, null=True)),
                ('license_number', models.CharField(max_length=100, unique=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('clinic_name', models.CharField(blank=True, max_length=200, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=200)),
                ('dosage', models.CharField(max_length=100)),
                ('frequency', models.CharField(help_text='e.g., Twice daily, Once a day', max_length=100)),
                ('duration', models.CharField(help_text='e.g., 5 days, 1 week', max_length=100)),
                ('route', models.CharField(blank=True, help_text='e.g., Oral, Injection, Topical', max_length=50, null=True)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('instructions', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='Pregnancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmation_date', models.DateField(help_text='Date when pregnancy was confirmed')),
                ('pregnancy_status', models.CharField(choices=[('suspected', 'Suspected'), ('confirmed', 'Confirmed'), ('failed', 'Failed'), ('aborted', 'Aborted'), ('delivered', 'Delivered')], default='suspected', max_length=20)),
                ('expected_delivery_date', models.DateField()),
                ('actual_delivery_date', models.DateField(blank=True, null=True)),
                ('pregnancy_duration', models.IntegerField(blank=True, help_text='Duration in days', null=True)),
                ('calf_gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=10, null=True)),
                ('calf_weight', models.DecimalField(blank=True, decimal_places=2, help_text='Weight in kg', max_digits=5, null=True)),
                ('delivery_type', models.CharField(blank=True, help_text='Normal/C-Section/Assisted', max_length=50, null=True)),
                ('complications', models.TextField(blank=True, null=True)),
                ('doctor_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ai_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pregnancy', to='core.artificialinsemination')),
                ('confirmed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.doctor')),
                ('cow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pregnancies', to='core.cow')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_pregnancies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Pregnancies',
                'ordering': ['-confirmation_date'],
            },
        ),
        migrations.CreateModel(
            name='Vaccination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccine_name', models.CharField(max_length=200)),
                ('disease_prevention', models.CharField(help_text='Disease this vaccine prevents', max_length=200)),
                ('vaccination_date', models.DateField(default=django.utils.timezone.now)),
                ('next_due_date', models.DateField(blank=True, null=True)),
                ('batch_number', models.CharField(blank=True, max_length=100, null=True)),
                ('dosage', models.CharField(max_length=100)),
                ('route', models.CharField(help_text='e.g., Subcutaneous, Intramuscular', max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('administered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.doctor')),
                ('cow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccinations', to='core.cow')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-vaccination_date'],
            },
        ),
        migrations.CreateModel(
            name='VeterinaryVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateField(default=django.utils.timezone.now)),
                ('visit_time', models.TimeField(default=django.utils.timezone.now)),
                ('visit_type', models.CharField(choices=[('routine', 'Routine Checkup'), ('emergency', 'Emergency'), ('vaccination', 'Vaccination'), ('ai', 'Artificial Insemination'), ('pregnancy_check', 'Pregnancy Check'), ('treatment', 'Treatment'), ('other', 'Other')], default='routine', max_length=20)),
                ('reason_for_visit', models.TextField()),
                ('symptoms', models.TextField(blank=True, null=True)),
                ('diagnosis', models.TextField(blank=True, null=True)),
                ('treatment_given', models.TextField(blank=True, null=True)),
                ('doctor_instructions', models.TextField(blank=True, help_text='Special instructions from doctor', null=True)),
                ('next_visit_date', models.DateField(blank=True, null=True)),
                ('visit_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='veterinary_visits', to='core.cow')),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits', to='core.doctor')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_visits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-visit_date', '-visit_time'],
            },
        ),
        migrations.DeleteModel(
            name='VeterinaryRecord',
        ),
        migrations.AddField(
            model_name='medicine',
            name='visit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicines', to='core.veterinaryvisit'),
        ),
        migrations.AddField(
            model_name='artificialinsemination',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.doctor'),
        ),
        migrations.AddField(
            model_name='artificialinsemination',
            name='recorded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
